version: '3'
services:
  server:
    image: gitlab/gitlab-ee:latest
    restart: always
    hostname: '${GITLAB_HOSTNAME}'
    environment:
      GITLAB_ROOT_PASSWORD: '${GITLAB_ROOT_PASSWORD}'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_HOSTNAME}:${GITLAB_HTTP_PORT}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
    ports:
      - '${GITLAB_HTTP_PORT}:${GITLAB_HTTP_PORT}'
      - '${GITLAB_SSH_PORT}:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
  
  runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - ${DOCKER_SOCK}:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
    
volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner-config:
